name: ci

on:
  pull_request:
    paths:
      - '*/**'
      - '!.azure-pipelines/**'
      - '!src/**'
      - '!msgraph-cli.sln'

jobs:
  build:
    name: "Microsoft Graph CLI - Release"
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
